name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
    - name: Determine release version
      run: docker run --rm -v $(pwd):/mnt kune/git-dev-flow /mnt; pwd; ls -la; export tmp_dir=$(mktemp -d); tar cvfz $tmp_dir/dump.tgz $(pwd); ls -la $tmp_dir
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{tmp_dir}}/dump.tgz
